### ISSUE TITLE
Documentation subtitle is about Stripe instead of DatoCMS

### ISSUE THREAD

**Issue by floriangosse** [datocms/new-website#11]
Documentations has a subtitle that talks about Stripe instead of DatoCMS:

https://github.com/datocms/new-website/blob/057a4145ab376987b0068611279cd6c3b192bc94/pages/docs/index.js#L91-L93

**Comment by stefanoverna** [comment]
Whoops. That's embarassing :) Thanks for letting us know :)

**Comment by floriangosse** [comment]
I won't tell anyone. 🤐
