### ISSUE TITLE
[Feature Request] Add in-page anchors for headings in Markdown files

### ISSUE THREAD

**Issue by arcataroger** [datocms/new-website#39]
For a long page like https://www.datocms.com/security, we have a lot of headers but no in-page anchors to navigate between them.

This makes it difficult to deep-link to a specific section, like the part talking about 2FA (way down the page, under "What the users can do to protect their account").

I think we should be able to use a couple of `react-markdown` plugins to automatically accomplish this:

-  https://github.com/rehypejs/rehype-slug
-  https://github.com/rehypejs/rehype-autolink-headings#rehype-autolink-headings

The page Markdown text is at https://github.com/datocms/new-website/blob/master/pages/legal/docs/security.md, and it gets parsed in https://github.com/datocms/new-website/blob/master/pages/security/index.js#L14-L39. The plugins should be able to generate anchors from the Markdown headings and add links to themselves.

How does that sound?

------------------

I'll make a PR for that when I have time, unless someone wants to do it sooner?

**Comment by stefanoverna** [comment]
Done! https://github.com/datocms/new-website/commit/9131dc1b8596035013a4f6235860b04d56fb6095

**Comment by arcataroger** [comment]
> Done! [9131dc1](https://github.com/datocms/new-website/commit/9131dc1b8596035013a4f6235860b04d56fb6095)

Nice, thank you!! I'll update the links shortly :)

**Comment by arcataroger** [comment]
Was `<DocDescription/>` something we're previously used for other pages, and these last few were just stragglers that we missed?

**Comment by stefanoverna** [comment]
Yes!
