### ISSUE TITLE
Update documentation examples with `curl -g`

### ISSUE THREAD

**Issue by arcataroger** [datocms/new-website#56]
@delphaber reported this in another code review:

https://github.com/datocms/api/pull/392#discussion_r1492626061

> I think we need to make another change to the website repo, because the `curl` examples containing square brackets in the URL are not working without the `-g` option.
> 
> From this:
> 
> ```shell
> curl 'https://site-api.datocms.com/items?page[offset]=1&page[limit]=2' \
>   -H "Authorization: Bearer YOUR-API-TOKEN" \
>   -H "Accept: application/json" \
>   -H "X-Api-Version: 3"
> ```
> 
> To this:
> 
> ```shell
> curl -g 'https://site-api.datocms.com/items?page[offset]=1&page[limit]=2' \
>   -H "Authorization: Bearer YOUR-API-TOKEN" \
>   -H "Accept: application/json" \
>   -H "X-Api-Version: 3"
> ```

**Comment by stefanoverna** [comment]
Fixed!
